# Generated by Django 5.2 on 2025-04-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under review', 'Under review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50),
        ),
    ]
