# Generated by Django 5.2 on 2025-04-16 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('application_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='main.applicationuser')),
            ],
        ),
    ]
