# Generated by Django 5.2 on 2025-04-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_applicationissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationissue',
            name='application_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.applicationuser'),
        ),
    ]
