# Generated by Django 5.2 on 2025-04-16 07:05

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_applicationissue_application_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='passport_serial',
            field=models.CharField(help_text='Pasport seriyasi va raqami, masalan: AA1234567', max_length=9, validators=[main.models.validate_passport]),
        ),
    ]
